#ifndef __GAME_STATE__
#define __GAME_STATE__

typedef enum GAME_STATE {
  GAME_STATE_MENU = 0,
  GAME_STATE_LEVEL_ONE,
  GAME_STATE_TRANSITION,
  GAME_STATE_LEVEL_TWO,
  GAME_STATE_VICTORY,
  GAME_STATE_GAME_OVER
} GAME_STATE;

#endif  // __GAME_STATE__